name: 友链模板
description: 自助添加友链。
labels: ['Reviewing']
body:
  - type: textarea
    id: json-data
    validations:
      required: true
    attributes:
      label: 友链信息
      description: |
        请在下方的 `JSON` 块中填写，不要修改格式。
        | 字段        | 说明                |
        | ----------- | ------------------- |
        | title       | 友链标题 (必填项)   |
        | url         | 友链地址 (必填项)   |
        | icon        | 网站图标 (必填项)   |
        | description | 一句话简介 (必填项) |
        | snapshot    | 网站截图            |
        | feed        | RSS订阅地址         |

      value: |
        ```json
        {
            "title": "",
            "url": "",
            "icon": "",
            "snapshot": "",
            "description": "",
            "feed": ""
        }
        ```
  - type: input
    id: friends-html
    attributes:
      label: 友链地址
      description: 请输入您的友链页面地
      placeholder: "如: https://wells.host/friendlink/"
    validations:
      required: true
  - type: input
    id: friends-repo
    attributes:
      label: 友链仓库（可选）
      description: 如果您使用 issue 作为友链源，请附上 issue 仓库链接
      placeholder: "如: https://github.com/we11s/blog-friends"
