name: Links Checker

on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled]
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  reachability-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Reachability
        uses: xaoxuu/links-checker@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          checker: 'reachability'
          unreachable_label: 'Offline'
          accepted_codes: '200,201,202,203,204,205,206,300,301,302,303,304,307,308,429'
          exclude_issue_with_labels: 'Reviewing'

      - name: Generate data.json
        uses: xaoxuu/issues2json@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sort: 'posts-desc'
          exclude_issue_with_labels: 'Reviewing'
          hide_labels: ''

      - name: Setup Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Commit and Push to output branch
        run: |
          git fetch origin output || true
          git checkout -B output
          git add --all
          git commit -m "Update data from issues" || echo "No changes to commit"
          git push -f origin output
